services:
  - type: web
    name: yasser-grammar-test
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true 